- name: for Git in Sky
  hosts: all
  become: yes

  roles:
     - { role: initial_settings, when: ansible_os_family == "Debian"  }
     - { role: create_TLS_key }
     - { role: add_virthost_file }  
