---
# tasks file for add_virthost_file
- name: copying a web page from a git
  get_url:
    url: '{{ first_page }}'
    dest: '{{ default_directory }}'
  tags: copying_page

    #если нужено будет копирвоать страницу в виде архива
    #name: unzipp web page to /var/www 
    #unarchive:
    #src: /tmp/*******************.zip
    #dest: /var/www/
    #remote_src: yes
    #tags: copying_page

- name: copy new virthost file
  template:
   src:  "{{ virt_host }}.j2"
   dest: /etc/nginx/sites-available/virthost
   mode: 0644
  tags: virthost
  notify:
   - NGINX_reload

- name: Create a symbolic link
  file:
   src: /etc/nginx/sites-available/virthost
   dest: /etc/nginx/sites-enabled/default
   state: link
  tags: virthost
  notify:
    - NGINX_reload
