---
   - name: Update apt
     apt: update_cache=yes
     when: ansible_os_family == "Debian"
     tags: install

   - name: install pkg
     apt:
      pkg: ['zsh=5.4*','wget=1.19.4*', 'unzip', 'nginx=1.14.*', 'letsencrypt']
     when: ansible_os_family == "Debian"
     tags: install

   - name:  changed net.core.somaxconn
     sysctl:
      name: net.core.somaxconn
      value: '{{ net_core_somaxconn | default 65535 }}'
      sysctl_set: yes
     tags: sysctl


   - name:  changed fs.file-max
     sysctl:
      name: fs.file-max
      value: '{{ fs_file_max | default 1204000 }}'
      sysctl_set: yes
     tags: sysctl

   - name: add user admin
     user:
       name: admin
       password: '{{ User_password }}'
       shell: /bin/bash
       groups: sudo
       append: yes
      tags: add_user


   - name: Set up multiple authorized keys to admin
     authorized_key:
       user: admin
       state: present
       key: '{{ item }}'
     with_file:
     - first_key_rsa.pub
     - second_key_rsa.pub
     tags: add_ssh_key
